### ISSUE TITLE
Weights Initialization naming issue

### ISSUE THREAD

**Issue by aleksmirosh** [NASA-IMPACT/hls-foundation-os#56]
Hello, once again thank you for sharing this amazing model, it is much better all I tested before.
I think there is an issue for pre-trained model initialization during testing.
I use this line:
`mim test mmsegmentation configs/sen1floods11_config.py --checkpoint /my_path/checkpoint/sen1floods11_Prithvi_100M.pth --eval "mIoU"`

And I got:
`unexpected key in source state_dict: neck.fpn1.0.weight, neck.fpn1.0.bias, neck.fpn1.1.ln.weight, neck.fpn1.1.ln.bias, neck.fpn1.3.weight, neck.fpn1.3.bias, neck.fpn2.0.weight, neck.fpn2.0.bias, neck.fpn2.1.ln.weight, neck.fpn2.1.ln.bias, neck.fpn2.3.weight, neck.fpn2.3.bias, decode_head.conv_seg.weight, decode_head.conv_seg.bias, decode_head.convs.0.conv.weight, decode_head.convs.0.bn.weight, decode_head.convs.0.bn.bias, decode_head.convs.0.bn.running_mean, decode_head.convs.0.bn.running_var, decode_head.convs.0.bn.num_batches_tracked, auxiliary_head.conv_seg.weight, auxiliary_head.conv_seg.bias, auxiliary_head.convs.0.conv.weight, auxiliary_head.convs.0.bn.weight, auxiliary_head.convs.0.bn.bias, auxiliary_head.convs.0.bn.running_mean, auxiliary_head.convs.0.bn.running_var, auxiliary_head.convs.0.bn.num_batches_tracked, auxiliary_head.convs.1.conv.weight, auxiliary_head.convs.1.bn.weight, auxiliary_head.convs.1.bn.bias, auxiliary_head.convs.1.bn.running_mean, auxiliary_head.convs.1.bn.running_var, auxiliary_head.convs.1.bn.num_batches_tracked`

Is it something because of using MMCV? Could you please explain how to modify keys in checkpoint so weights load correctly?
I have the same problem with weights even after finetune.

**Comment by aleksmirosh** [comment]
Nevermind.
It is triggered by ViT. Thats correct

**Comment by longdaothanh** [comment]
> Nevermind. It is triggered by ViT. Thats correct

Do you how to fix this? Thanks
